# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Giddy
email: asergienko@bk.ru
description: > # this means to ignore newlines until "baseurl:"
  Мой блог об изучении программирования, английского, и вообще о моей жизни
baseurl: "" # the subpath of your site, e.g. /blog
url: https://giddy.me
#url: "https://sergalexand.github.io/" # the base hostname & protocol for your site
twitter_username: alex_mhf
github_username:  sergalexand
instagram_username: sergienko_alexey_

# Build settings
markdown: kramdown

# do you want to show the "tags" inside the posts?
show-tags: true
# do you want to show the "read time" of the posts?
read-time: true
# related posts inside a post?
related: true
# Display links for next and previous posts for the specified categories
post-advance-links: [blog]
# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate
